# Site settings ...
uri: 930114.xyz
url: https://930114.xyz
name: Ivan
title: 咦嘻嘻~
email: alphazhu@hotmail.com
author: Alpha
baseurl: ""
keywords: "Your, Keyword, Here"
description: "Some of us get dipped in flat, some in satin, some in gloss. But every once in a while you find someone who's iridescent, and when you do, nothing will ever compare."
social_username: Alpha

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
